### ISSUE TITLE
Tests failing with ENOENT

### ISSUE THREAD

**Issue by tomljones** [janjakubnanista/wd-video-recorder#1]
I found my problem, ffmpeg was not found in the path. Once I moved it to the path the problem went away.

I cloned your project and took the following steps
1. git clone
2. npm install
3. edited grunt file to include path to mocha 
"command: 'node_modules/mocha/bin/mocha --reporter spec --colors test/*.js',"
4. ran "grunt test"

Most of the tests fail with 

  1) Recorder save method should save all frames from tmpdir to a video file:
     Uncaught Error: spawn ENOENT
      at errnoException (child_process.js:988:11)
      at Process.ChildProcess._handle.onexit (child_process.js:779:34)

I did check the obvious permission problems and it is still failing. Any ideas?

**Comment by jskulski** [comment]
Just quoting from the original post because I missed it and came back to this issue a couple times in my searching.

"I found my problem, ffmpeg was not found in the path. Once I moved it to the path the problem went away."
